steps:
  # Step 1: Update submodules in the cloned repository.
  - name: 'gcr.io/cloud-builders/git'
    dir: 'hydrator-plugins'
    args: ['submodule', 'update', '--init', '--recursive', '--remote']

  # Step 2: Run the Maven build.
  - name: 'maven:3.6.3-jdk-11'
    dir: 'hydrator-plugins'
    args: ['clean', 'package']

