# Resource
# https://stackoverflow.com/questions/70973259/github-action-for-synching-a-fork

name: Sync Fork with Upstream

# Trigger daily
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configure Git and add the original repo
      - name: Setup Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # replace URL with your upstream repo:
          git remote add upstream https://github.com/cdapio/hydrator-plugins.git
          git fetch upstream

      # Merge upstream changes
      - name: Merge upstream into main
        run: |
          git checkout develop
          git merge upstream/develop

      # Push the updated branch
      - name: Push changes
        run: git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
